ALTER TABLE documents ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS security_level VARCHAR(20) DEFAULT 'NORMAL';
ALTER TABLE documents ADD COLUMN IF NOT EXISTS metadata JSONB;
